### ISSUE TITLE
Java Illegal Argument Exception

### ISSUE THREAD

**Issue by Sadasak** [thebaselab/codeapp#1105]
I'm trying to run a java code and it's not working as it gives me an Illegal Argument Exception. Mentioning that the same code is smoothly executed on other IDEs or even online compiler

This is the code:
```

package procedural;

	import java.util.ArrayList;
	import java.util.List;

	public class Procedural {
		
		public static void main(String[] args) {
			System.out.println(initializeWalletBalance(1000.3));
			
			System.out.println(receive("Salary", "Company", 500.0));
			System.out.println(spend("Shawerma", "Saj", 2.25));
			System.out.println(receive("Freelance", "Client", 25.0));// it's cheaper than the oop cause its easier :)
			System.out.println(spend("Fees", "HTU", 362.5));
			System.out.println( );
			
			System.out.println("Sorting by Price:");
			selectionSortByAmount();
			for (int i = 0; i < processCounter; i++) {
				printProcessInfo(i);
			}
			
			System.out.println();

			System.out.println("Sorting by ID:");
			selectionSortByID();
			for (int i = 0; i < processCounter; i++) {
				printProcessInfo(i);
			}
			
			System.out.println();

			System.out.println("Wallet Balance: " + walletBalance);
		}

		// array for each attribute to contain all values
	    // i used list cause i don't want to make a limit for the processes
	    static List<Character> processTypes = new ArrayList<>();
	    static List<String> processNames = new ArrayList<>();
	    static List<String> processStakeholders = new ArrayList<>();
	    static List<Double> processAmounts = new ArrayList<>();
	    static List<Integer> processIDs = new ArrayList<>();
	    static double walletBalance = 0.0;
	    static int processCounter = 0;

	    // function to initialize wallet balance and return it to print it
	    public static double initializeWalletBalance(double balance) {
	        walletBalance = balance;
			return balance;
	    }

	    // function to put receive process and return a string saies what happend to the process
	    public static String receive(String name, String stakeholder, double profit) {
	        if (isNotValid(profit)) {
				return "invalid procces: the profit must be bigger that zero";
	        }
	        walletBalance += profit;
	        processTypes.add('R');
	        processNames.add(name);
	        processStakeholders.add(stakeholder);
	        processAmounts.add(profit);
	        processCounter++;
	        processIDs.add(processCounter);
			return "success process ";
	    }

	    // function to put spend process and return a string saies what happend to the process
	    public static String spend(String name, String stakeholder, double price) {
	        if (isNotValid(price)) {
				return "invalid procces: the price must be bigger that zero";
	        }
	        walletBalance -= price;
	        processTypes.add('S');
	        processNames.add(name);
	        processStakeholders.add(stakeholder);
	        processAmounts.add(price);
	        processCounter++;
	        processIDs.add(processCounter);
			return "success process ";
	    }

		// to check if the price or profit is valid
		public static boolean isNotValid(double money){
			return money <= 0;
		}

	    // function to sort processes by amount of money
	    public static void selectionSortByAmount() {
	        for (int i = 0; i < processCounter - 1; i++) {
	            int maxIndex = i;
	            for (int j = i + 1; j < processCounter; j++) {
	                if (processAmounts.get(j) > processAmounts.get(maxIndex)) {
	                    maxIndex = j;
	                }
	            }
	            swapProcesses(i, maxIndex);
	        }
	    }

	    // function to sort processes by ID
	    public static void selectionSortByID() {
	        for (int i = 0; i < processCounter - 1; i++) {
	            int minIndex = i;
	            for (int j = i + 1; j < processCounter; j++) {
	                if (processIDs.get(j) < processIDs.get(minIndex)) {
	                    minIndex = j;
	                }
	            }
	            swapProcesses(i, minIndex);
	        }
	    }

	    // it is easier to make it a separated function or method cause it's too long
	    public static void swapProcesses(int i, int j) {
	        char tempType = processTypes.get(i);
	        String tempName = processNames.get(i);
	        String tempStakeholder = processStakeholders.get(i);
	        double tempAmount = processAmounts.get(i);
	        int tempID = processIDs.get(i);

	        processTypes.set(i, processTypes.get(j));
	        processNames.set(i, processNames.get(j));
	        processStakeholders.set(i, processStakeholders.get(j));
	        processAmounts.set(i, processAmounts.get(j));
	        processIDs.set(i, processIDs.get(j));

	        processTypes.set(j, tempType);
	        processNames.set(j, tempName);
	        processStakeholders.set(j, tempStakeholder);
	        processAmounts.set(j, tempAmount);
	        processIDs.set(j, tempID);
	    }

	    // function to print the info of a process
	    public static void printProcessInfo(int index) {
	        if (processTypes.get(index).equals('R')) {
	            System.out.println(processIDs.get(index) + "  " + processNames.get(index) + ": \t\t" + processStakeholders.get(index) + " \t\t+" + processAmounts.get(index));
	        } else if (processTypes.get(index).equals('S')) {
	            System.out.println(processIDs.get(index) + "  " + processNames.get(index) + ": \t\t" + processStakeholders.get(index) + " \t\t-" + processAmounts.get(index));
	        }
	    }
	}

```

And it throws this for me:

```

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.IllegalArgumentException: Error decoding percent encoded characters
        at sun.net.www.ParseUtil.decode(ParseUtil.java:216)
        at sun.misc.URLClassPath$FileLoader.<init>(URLClassPath.java:1336)
        at sun.misc.URLClassPath$3.run(URLClassPath.java:570)
        at sun.misc.URLClassPath$3.run(URLClassPath.java:565)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.misc.URLClassPath.getLoader(URLClassPath.java:564)
        at sun.misc.URLClassPath.getLoader(URLClassPath.java:529)
        at sun.misc.URLClassPath.getNextLoader(URLClassPath.java:494)
        at sun.misc.URLClassPath.getResource(URLClassPath.java:248)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)

```

**Comment by bummoblizard** [comment]
This is likely an issue related to the source code's file path. Please make sure it doesn't contain special characters. Alternatively, try invoking the javac / java command manually in the terminal.

**Comment by Sadasak** [comment]
Yes, I put an emoji on the folder's name and it was the issue.

Thanks
