### ISSUE TITLE
I have a problem with install a node module

### ISSUE THREAD

**Issue by Arioch-IV** [thebaselab/codeapp#49]
When I try to install canvacord with npm, the console write this ![image](https://user-images.githubusercontent.com/78066493/111257008-b9283f80-85f0-11eb-922e-45be8c40c4f7.png)

**Comment by bummoblizard** [comment]
Hi, `canvacord` contains native module. It is therefore not supported.

**Comment by bummoblizard** [comment]
Here’s the full error message:
```
npm WARN deprecated node-pre-gyp@0.15.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code EPERM
npm ERR! syscall spawn
npm ERR! errno EPERM
npm ERR! Error: spawn EPERM
npm ERR!     at ChildProcess.spawn (internal/child_process.js:407:11)
npm ERR!     at spawn (child_process.js:553:9)
npm ERR!     at /private/var/containers/Bundle/Application/23BDF03E-5E49-487D-8861-8D7B8F2117B0/Code.app/npm.bundle/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:36:12
npm ERR!     at new Promise (<anonymous>)
npm ERR!     at promiseSpawnUid (/private/var/containers/Bundle/Application/23BDF03E-5E49-487D-8861-8D7B8F2117B0/Code.app/npm.bundle/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:35:13)
npm ERR!     at promiseSpawn (/private/var/containers/Bundle/Application/23BDF03E-5E49-487D-8861-8D7B8F2117B0/Code.app/npm.bundle/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:15:10)
npm ERR!     at runScriptPkg (/private/var/containers/Bundle/Application/23BDF03E-5E49-487D-8861-8D7B8F2117B0/Code.app/npm.bundle/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:66:5)
npm ERR!     at runScript (/private/var/containers/Bundle/Application/23BDF03E-5E49-487D-8861-8D7B8F2117B0/Code.app/npm.bundle/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:16)
npm ERR!     at Array.<anonymous> (/private/var/containers/Bundle/Application/23BDF03E-5E49-487D-8861-8D7B8F2117B0/Code.app/npm.bundle/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/rebuild.js:286:17)
npm ERR!     at run (/private/var/containers/Bundle/Application/23BDF03E-5E49-487D-8861-8D7B8F2117B0/Code.app/npm.bundle/node_modules/npm/node_modules/promise-call-limit/index.js:30:26)
npm ERR!  Error: spawn EPERM
npm ERR!     at ChildProcess.spawn (internal/child_process.js:407:11)
npm ERR!     at spawn (child_process.js:553:9)
npm ERR!     at /private/var/containers/Bundle/Application/23BDF03E-5E49-487D-8861-8D7B8F2117B0/Code.app/npm.bundle/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:36:12
npm ERR!     at new Promise (<anonymous>)
npm ERR!     at promiseSpawnUid (/private/var/containers/Bundle/Application/23BDF03E-5E49-487D-8861-8D7B8F2117B0/Code.app/npm.bundle/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:35:13)
npm ERR!     at promiseSpawn (/private/var/containers/Bundle/Application/23BDF03E-5E49-487D-8861-8D7B8F2117B0/Code.app/npm.bundle/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:15:10)
npm ERR!     at runScriptPkg (/private/var/containers/Bundle/Application/23BDF03E-5E49-487D-8861-8D7B8F2117B0/Code.app/npm.bundle/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:66:5)
npm ERR!     at runScript (/private/var/containers/Bundle/Application/23BDF03E-5E49-487D-8861-8D7B8F2117B0/Code.app/npm.bundle/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:16)
npm ERR!     at Array.<anonymous> (/private/var/containers/Bundle/Application/23BDF03E-5E49-487D-8861-8D7B8F2117B0/Code.app/npm.bundle/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/rebuild.js:286:17)
npm ERR!     at run (/private/var/containers/Bundle/Application/23BDF03E-5E49-487D-8861-8D7B8F2117B0/Code.app/npm.bundle/node_modules/npm/node_modules/promise-call-limit/index.js:30:26) {
npm ERR!   errno: 'EPERM',
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'spawn'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
npm ERR! Cannot read property 'stdin' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/mobile/Containers/Data/PluginKitPlugin/D5748C46-DCBF-495B-A76C-98E46FF13E44/Library/Caches/_logs/2021-03-16T05_37_16_311Z-debug.log
```

The installation script of canvacord uses childProcess.spawn, which is unsupported in iOS.

**Comment by bummoblizard** [comment]
Closing this for now.

**Comment by shubhankartrivedi** [comment]
I have the same problem while installing “vite” npm module. Can you check and let me know.
