### ISSUE TITLE
Error with sklearn.model_selection.cross_val_score

### ISSUE THREAD

**Issue by carlossierra311** [thebaselab/codeapp#69]
Hi CodeApp team. 

When I run this sample code:
```
# correct data preparation for model evaluation with k-fold cross-validation
from numpy import mean
from numpy import std
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
# define dataset
X, y = make_classification(n_samples=1000, n_features=20, n_informative=15, n_redundant=5, random_state=7)
# define the pipeline
steps = list()
steps.append(('scaler', MinMaxScaler()))
steps.append(('model', LogisticRegression()))
pipeline = Pipeline(steps=steps)
# define the evaluation procedure
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate the model using cross-validation
scores = cross_val_score(pipeline, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
# report performance
print('Accuracy: %.3f (%.3f)' % (mean(scores)*100, std(scores)*100))
```

I get this error message:

```
../compiled/joblib/externals/loky/backend/resource_tracker.py:120: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some folders/sempahores might leak.
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/AE37A578-E67A-4738-880C-DB1A18573B68/File Provider Storage/Machine Learning/Data Preparation for Machine Learning/code/chapter_04/05_cv_eval_correct.py", line 20, in <module>
    scores = cross_val_score(pipeline, X, y, scoring='accuracy', cv=cv, n_jobs=-1)
  File "../../../downloadable-site-packages/compiled/sklearn/utils/validation.py", line 60, in inner_f
  File "../../../downloadable-site-packages/compiled/sklearn/model_selection/_validation.py", line 440, in cross_val_score
  File "../../../downloadable-site-packages/compiled/sklearn/utils/validation.py", line 60, in inner_f
  File "../../../downloadable-site-packages/compiled/sklearn/model_selection/_validation.py", line 246, in cross_validate
  File "../compiled/joblib/parallel.py", line 966, in __call__
  File "../compiled/joblib/parallel.py", line 733, in _initialize_backend
  File "../compiled/joblib/_parallel_backends.py", line 494, in configure
  File "../compiled/joblib/executor.py", line 20, in get_memmapping_executor
  File "../compiled/joblib/executor.py", line 42, in get_memmapping_executor
  File "../compiled/joblib/_memmapping_reducer.py", line 531, in __init__
  File "../compiled/joblib/_memmapping_reducer.py", line 535, in set_current_context
  File "../compiled/joblib/_memmapping_reducer.py", line 560, in register_new_context
  File "../compiled/joblib/_memmapping_reducer.py", line 590, in register_folder_finalizer
  File "../compiled/joblib/externals/loky/backend/resource_tracker.py", line 191, in register
  File "../compiled/joblib/externals/loky/backend/resource_tracker.py", line 209, in _send
BrokenPipeError: [Errno 32] Broken pipe
>>> 
```

Any ideas on how to solve it?

Thanks

**Comment by bummoblizard** [comment]
Hi. `Sklearn` isn’t currently supported by the local runtime because it requires a module that is not yet ported to iOS. I’m unsure how you reach that far though. Can you share how you installed sklearn?

**Comment by carlossierra311** [comment]
I tried:
`pip install sklearn`

But that did fail. I also tried using the built-in PyPi installation, but this is what happens:
![image](https://user-images.githubusercontent.com/23511373/112821754-b562d700-904c-11eb-8c00-a386ae0163fe.png)

Finally, when running another python script, I think I saw Pyto trying to install some (¿older?) versions of sklearn automatically, but it got in some sort of loop, so I just closed the app.

**Comment by bummoblizard** [comment]
After a quick look it seems like Pyto has built in support for `sklearn`. I'm afraid it isn't something Code App supports currently. 

You should probably run the code inside Pyto and perhaps ask Pyto's author regarding this.
