### ISSUE TITLE
pip无法换源

### ISSUE THREAD

**Issue by Tom1246** [thebaselab/codeapp#745]
克隆仓库的时候，使用pip config set global.index-url指令换源，报错如下：

Documents $ pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

Writing to /private/var/mobile/Containers/Data/Application/DE3D3638-F3E1-448C-81A8-C1F00003C00B/.config/pip/pip.conf
ERROR: Unable to save configuration. Please report this as a bug.
Traceback (most recent call last):
  File "/private/var/containers/Bundle/Application/80CF8BF2-3DFD-471B-8680-2B988B985D55/Code.app/Library/lib/python3.9/site-packages/pip/_internal/commands/configuration.py", line 264, in _save_configuration
    self.configuration.save()
  File "/private/var/containers/Bundle/Application/80CF8BF2-3DFD-471B-8680-2B988B985D55/Code.app/Library/lib/python3.9/site-packages/pip/_internal/configuration.py", line 223, in save
    ensure_dir(os.path.dirname(fname))
  File "/private/var/containers/Bundle/Application/80CF8BF2-3DFD-471B-8680-2B988B985D55/Code.app/Library/lib/python3.9/site-packages/pip/_internal/utils/misc.py", line 110, in ensure_dir
    os.makedirs(path)
  File "/private/var/containers/Bundle/Application/80CF8BF2-3DFD-471B-8680-2B988B985D55/Code.app/Library/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/private/var/containers/Bundle/Application/80CF8BF2-3DFD-471B-8680-2B988B985D55/Code.app/Library/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 1] Operation not permitted: '/private/var/mobile/Containers/Data/Application/DE3D3638-F3E1-448C-81A8-C1F00003C00B/.config'
ERROR: Internal Error.

**Comment by bummoblizard** [comment]
`pip config set global.index-url --user https://pypi.tuna.tsinghua.edu.cn/simple`
